# Generated by Django 5.1.2 on 2024-11-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('club', 'Club'), ('admin', 'Admin')], default='player', max_length=10),
        ),
    ]
